tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-container": "#666565",
                "on-primary": "#470083",
                "on-secondary-container": "#007070",
                "on-tertiary-fixed": "#1c1b1b",
                "error": "#ffb4ab",
                "surface-container-low": "#1c1b1b",
                "on-surface-variant": "#cfc2d9",
                "on-tertiary-container": "#e6e3e2",
                "on-background": "#e5e2e1",
                "outline-variant": "#4d4356",
                "surface-container-lowest": "#0e0e0e",
                "background": "#131313",
                "error-container": "#93000a",
                "outline": "#988ca2",
                "on-primary-fixed": "#2b0053",
                "primary-fixed": "#efdbff",
                "on-error-container": "#ffdad6",
                "primary": "#dab9ff",
                "primary-fixed-dim": "#dab9ff",
                "inverse-surface": "#e5e2e1",
                "surface": "#131313",
                "surface-container": "#201f1f",
                "inverse-primary": "#8600ef",
                "on-tertiary-fixed-variant": "#474746",
                "surface-bright": "#3a3939",
                "on-primary-container": "#efddff",
                "primary-container": "#8f00ff",
                "secondary-fixed-dim": "#00dddd",
                "surface-container-highest": "#353534",
                "surface-dim": "#131313",
                "on-primary-fixed-variant": "#6500b8",
                "on-surface": "#e5e2e1",
                "on-tertiary": "#313030",
                "on-secondary-fixed": "#002020",
                "surface-variant": "#353534",
                "on-secondary": "#003737",
                "secondary-fixed": "#00fbfb",
                "secondary-container": "#00fbfb",
                "inverse-on-surface": "#313030",
                "surface-container-high": "#2a2a2a",
                "on-error": "#690005",
                "tertiary-fixed-dim": "#c8c6c5",
                "tertiary": "#c8c6c5",
                "on-secondary-fixed-variant": "#004f4f",
                "secondary": "#ffffff",
                "surface-tint": "#dab9ff",
                "tertiary-fixed": "#e5e2e1"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Space Grotesk"],
                "body": ["Be Vietnam Pro"],
                "label": ["Inter"]
            }
        },
    },
};
